# POSITIONS
spawnPosition:
  world: "World"
  x: 0.0
  y: 60.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
# MESSAGES
prefixMessage: "§7[§bGCore§7]: §f"
  # SPECIAL START: <player>
welcomeMessage: "§aGreat to see you §7<player> §ahave fun!"
  # SPECIAL END
deathTitleMessage: "§cYou died"
deathSubTitleMessage: "§7be careful next time"
# MODERATION MESSAGES
  # SPECIAL START: <player> & <reason>
broadcastKickMessage: "§7<player> §chave been kicked for <reason>"
  # SPECIAL END
kickMessage: "§cYou have been kicked"
# CHAT FILTER
messageFilter:
  - "fuck"
  - "bitch"
  - "puta"
# ROLES
playerRoles:
  - "New"
  - "Player"
  - "Vip"
  - "Helper"
  - "Moderator"
  - "Admin"
  - "Owner"
  # SPECIAL START: <player> & <rank> & <rank_color>
playerNameTag: "§f[<rank_color><rank>§f] <rank_color>"
  # SPECIAL END
  # SPECIAL START: <player> & <rank> & <rank_color> ([!] rank color can only be set one time)
generalChatFormat: "§f[<rank_color><rank>§f] <player>§f: §f"
  # SPECIAL END
