name: G-Core
version: '${version}'

main: fr.great.gCore.GCore
api-version: '26.2'
load: POSTWORLD

commands:
  spawn:
    description: Spawn related command
  role:
    description: Role related command
  gkick:
    description: Kick related command
  gmute:
    description: Mute related command
  gunmute:
    description: Unmute related command
  worldsettings:
    description: Settings related command
  world:
    description: World related command
