name: G-Core
version: '${version}'

main: fr.great.gCore.GCore
api-version: '26.2'
load: POSTWORLD

commands:
  spawn:
    description: Spawn related command
  role:
    description: Role related command
  gkick:
    description: Kick related command